### ISSUE TITLE
Add proxy endpoint to prevent CORS errors

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-viewer#9]
CORS is annoying. In the prod version of viewer, we cannot go straight to `kiosk-backend` because that's a cross-site request and we don't configure CORS in that way for SE API. Instead, we'll have to perform a fetch on the backend.

So, the request will look like this:

`GET /api/checkins` which will send a request to `GET kiosk-backend.cusmartevents.com/api/checkins`

**Comment by masnoble** [comment]
This should have been resolved as the API was restored to a stable state... 503 Error was due to broken api
